-- KPI role catalog transcribed from the supplied V3.1 workbook.
create table if not exists public.d4_kpi_role_catalog (
  role_order integer not null check (role_order between 1 and 10),
  role_name text not null,
  indicator_order integer not null check (indicator_order between 1 and 5),
  kpi_name text not null,
  target text,
  weight_percent integer not null check (weight_percent between 1 and 100),
  source_version text not null default 'V3.1',
  primary key (role_order, indicator_order),
  unique (role_name, kpi_name)
);
alter table public.d4_kpi_role_catalog enable row level security;
grant select on public.d4_kpi_role_catalog to anon, authenticated;
create policy "Read supplied KPI role catalog" on public.d4_kpi_role_catalog for select to anon, authenticated using (true);
insert into public.d4_kpi_role_catalog (role_order,role_name,indicator_order,kpi_name,target,weight_percent,source_version) values
  (1,'Vice President',1,'Pencapaian Target Laba Bersih Perusahaan',null,25,'V3.1'),
  (1,'Vice President',2,'Pertumbuhan Pendapatan (Revenue Growth) YoY',null,25,'V3.1'),
  (1,'Vice President',3,'Pengembangan Kemitraan Strategis & Lisensi Global',null,20,'V3.1'),
  (1,'Vice President',4,'Tingkat Retensi Karyawan Kunci / Key Talent Retention',null,15,'V3.1'),
  (1,'Vice President',5,'Kepatuhan Hukum & Manajemen Risiko',null,15,'V3.1'),
  (2,'Director',1,'Pencapaian Target Pendapatan Operasional',null,25,'V3.1'),
  (2,'Director',2,'Implementasi Rencana Strategis Perusahaan',null,20,'V3.1'),
  (2,'Director',3,'Efisiensi Biaya Operasional Keseluruhan',null,20,'V3.1'),
  (2,'Director',4,'Indeks Kepuasan Klien / Customer Satisfaction Score',null,20,'V3.1'),
  (2,'Director',5,'Pengembangan Portofolio Layanan Baru',null,15,'V3.1'),
  (3,'Operations Director',1,'Persentase Pengiriman Tepat Waktu / On-Time Delivery Rate',null,25,'V3.1'),
  (3,'Operations Director',2,'Zero Fatal Customs/Regulatory Penalty',null,25,'V3.1'),
  (3,'Operations Director',3,'Optimalisasi Pemanfaatan Kapasitas Gudang & Transport',null,20,'V3.1'),
  (3,'Operations Director',4,'Service Level Agreement (SLA) Resolution Time untuk Komplain',null,15,'V3.1'),
  (3,'Operations Director',5,'Indeks Produktivitas & Retensi Tim Operasional',null,15,'V3.1'),
  (4,'Branch Manager (Semarang, Surabaya, Balikpapan)',1,'Pencapaian Target Revenue Cabang',null,25,'V3.1'),
  (4,'Branch Manager (Semarang, Surabaya, Balikpapan)',2,'Pertumbuhan Klien Baru di Cabang',null,20,'V3.1'),
  (4,'Branch Manager (Semarang, Surabaya, Balikpapan)',3,'Efisiensi Biaya Operasional Cabang',null,20,'V3.1'),
  (4,'Branch Manager (Semarang, Surabaya, Balikpapan)',4,'SLA Operasional Cabang / Handling Time',null,20,'V3.1'),
  (4,'Branch Manager (Semarang, Surabaya, Balikpapan)',5,'Tingkat Retensi Karyawan Cabang',null,15,'V3.1'),
  (5,'Customs Clearance Expert / PPJK',1,'Kecepatan Proses Customs Clearance (PIB/PEB/BC1.1)',null,30,'V3.1'),
  (5,'Customs Clearance Expert / PPJK',2,'Akurasi Dokumen (Zero Error/Nota Pembetulan)',null,25,'V3.1'),
  (5,'Customs Clearance Expert / PPJK',3,'Kepatuhan Pembaruan Regulasi & Izin',null,15,'V3.1'),
  (5,'Customs Clearance Expert / PPJK',4,'Koordinasi Lapangan dengan Otoritas',null,15,'V3.1'),
  (5,'Customs Clearance Expert / PPJK',5,'Efektivitas Penanganan Jalur Merah',null,15,'V3.1'),
  (6,'Airfreight / Seafreight Operations Staff',1,'Akurasi Booking Space Maskapai/Shipping Line',null,25,'V3.1'),
  (6,'Airfreight / Seafreight Operations Staff',2,'Ketepatan Waktu Penerbitan Dokumen (AWB/BL)',null,25,'V3.1'),
  (6,'Airfreight / Seafreight Operations Staff',3,'Tingkat Keberhasilan Konsolidasi Kargo',null,20,'V3.1'),
  (6,'Airfreight / Seafreight Operations Staff',4,'Zero Claim/Damage pada Kargo Handler',null,15,'V3.1'),
  (6,'Airfreight / Seafreight Operations Staff',5,'Update Status Shipment ke Klien/Sales tepat waktu',null,15,'V3.1'),
  (7,'Warehousing / Logistics Staff',1,'Akurasi Inventory Gudang',null,25,'V3.1'),
  (7,'Warehousing / Logistics Staff',2,'Ketepatan Waktu Inbound/Outbound Process',null,25,'V3.1'),
  (7,'Warehousing / Logistics Staff',3,'Zero Safety Incident di Gudang',null,20,'V3.1'),
  (7,'Warehousing / Logistics Staff',4,'Kepatuhan Penanganan Dangerous Goods',null,15,'V3.1'),
  (7,'Warehousing / Logistics Staff',5,'Utilisasi Ruang Gudang',null,15,'V3.1'),
  (8,'Implant Staff (PEB, PIB, BC 1.1 Manifest Input)',1,'Akurasi Input Data ke Sistem Bea Cukai',null,35,'V3.1'),
  (8,'Implant Staff (PEB, PIB, BC 1.1 Manifest Input)',2,'Kecepatan Input Data (Lead Time per Job)',null,25,'V3.1'),
  (8,'Implant Staff (PEB, PIB, BC 1.1 Manifest Input)',3,'Ketersediaan & Disiplin Kerja di Lokasi Klien/Bea Cukai',null,20,'V3.1'),
  (8,'Implant Staff (PEB, PIB, BC 1.1 Manifest Input)',4,'Minimalisasi Kesalahan yang Mengakibatkan Penundaan',null,10,'V3.1'),
  (8,'Implant Staff (PEB, PIB, BC 1.1 Manifest Input)',5,'Komunikasi Efektif dengan Tim Operasional Utama',null,10,'V3.1'),
  (9,'Sales & Marketing',1,'Pencapaian Target Volume Sales (Air/Sea/Customs)',null,35,'V3.1'),
  (9,'Sales & Marketing',2,'Jumlah Akuisisi Klien Baru',null,25,'V3.1'),
  (9,'Sales & Marketing',3,'Akurasi Pemberian Quotation/Penawaran Harga',null,15,'V3.1'),
  (9,'Sales & Marketing',4,'Win Rate dari Total Quotation',null,15,'V3.1'),
  (9,'Sales & Marketing',5,'Kelancaran Serah Terima Order ke Tim Operasional',null,10,'V3.1'),
  (10,'Finance / Administration Staff',1,'Kecepatan Penerbitan Invoice (SLA < 24 jam)',null,25,'V3.1'),
  (10,'Finance / Administration Staff',2,'Akurasi Pembukuan & Input Krishand GL',null,25,'V3.1'),
  (10,'Finance / Administration Staff',3,'Ketepatan Waktu Pembayaran Vendor & Reimbursement',null,20,'V3.1'),
  (10,'Finance / Administration Staff',4,'Efektivitas Collection/Penagihan Piutang',null,15,'V3.1'),
  (10,'Finance / Administration Staff',5,'Kepatuhan Pelaporan Pajak & Kerapian Arsip',null,15,'V3.1')
on conflict (role_order, indicator_order) do update set
  role_name = excluded.role_name,
  kpi_name = excluded.kpi_name,
  target = excluded.target,
  weight_percent = excluded.weight_percent,
  source_version = excluded.source_version;
